// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gueikjqsuqupcgmvtsyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1ZWlranFzdXF1cGNnbXZ0c3loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3Njc3NzgsImV4cCI6MjA2NTM0Mzc3OH0.f8mxNiJfxb6ZO6sZDHAF82pyuWZf_j82KFA8aluC-O8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);